Fix CodeClimate Fix
[why]
When we add a dummy we need to remove that later on.

Originally that has been introduces to avoid a wrong code duplication
warning.

See how the blank leaks into the name:

ERROR: ====-< Family (ID 1)      too long (38 > 31): ZedMono Nerd Font Extended ExtraBold
DEBUG: =====> SubFamily (ID 2)   ok       ( 6 <=31): Italic
DEBUG: =====> Fullname (ID 4)    ok       (45 <=63): ZedMono Nerd Font Extended ExtraBold   Italic
DEBUG: =====> PSN (ID 6)         ok       (33 <=63): ZedMonoNF-ExtendedExtraBoldItalic
DEBUG: =====> PrefFamily (ID 16) ok       (17 <=31): ZedMono Nerd Font
DEBUG: =====> PrefStyles (ID 17) ok       (27 <=31): Extended ExtraBold   Italic
DEBUG: =====> PrefStyles (ID 17) ok       (27 <=31): Extended ExtraBold   Italic
DEBUG: =====> Filename 'ZedMonoNerdFont-ExtendedExtraBoldItalic.ttf'

(Note trailing blanks even in ID 1.)

Signed-off-by: Fini Jastrow <ulf.fini.jastrow@desy.de>